version: 2
jobs:
  build-and-test:
    working_directory: ~/ITKModuleTemplate-build
    docker:
      - image: insighttoolkit/module-ci:latest
    steps:
      - checkout:
          path: ~/ITKModuleTemplate
      - run:
          name: Configure
          command: |
            cmake \
              -G Ninja \
              -DITK_DIR:PATH=/ITK-build \
              -DBUILD_TESTING:BOOL=ON \
              -DBUILDNAME:STRING=External-ITKModuleTemplate-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} \
                ~/ITKModuleTemplate
      - run:
          name: Build and Test
          no_output_timeout: 1.0h
          command: |
            ctest -j 2 -VV -D Experimental
  package:
    working_directory: ~/ITKModuleTemplate
    machine: true
    steps:
      - checkout
      - run:
          name: Fetch build script
          command: |
            curl -L https://cdn.jsdelivr.net/gh/InsightSoftwareConsortium/ITKPythonPackage/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh -O
            chmod u+x dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            ./dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - store_artifacts:
          path: dist
          destination: dist

workflows:
    version: 2
    build-test-package:
      jobs:
        - build-and-test
        - package
